import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'
import { version } from './../package.json';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Learning App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <h1>
            <Link href="/">Learning App</Link>
          </h1>
        </header>
        <main className='u-p-1'>
          {children}
        </main>
        <footer>
          v{version}
        </footer>
      </body>
    </html>
  )
}
